version: "3"
services:
  web:
    container_name: web
    image: thaichain/explorer
    restart: "always"
    command: "server -d /explorer/ -m mongodb:27017 -signers /signers/signers.json  -u https://rpc.dome.cloud"
    links:
        - "mongodb"
    volumes:
        - ./signers:/signers
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "8080:8080"
    depends_on:
      - mongodb
  grabber:
    container_name: grabber
    image: thaichain/explorer
    restart: "always"
    command: "grabber -m mongodb:27017 -u http://51.15.80.113:8545"
    links:
        - "mongodb"
    depends_on:
      - mongodb
  mongodb:
        image: mongo
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        command: mongod --logpath=/dev/null

